SELECT * FROM TABELA_DE_CLIENTES;

SELECT * FROM tabela_de_produtos;

SELECT CPF, NOME, ENDERECO1, ENDERECO2, BAIRRO, CIDADE, ESTADO, CEP, IDADE, SEXO, LIMITE_CREDITO
FROM TABELA_DE_CLIENTES;

SELECT NOME, IDADE, DATA_NASCIMENTO
FROM TABELA_DE_CLIENTES;



