-- RETORNA A DATA DO SERVIDOR
SELECT SYSDATE FROM DUAL;

-- RETORNA A DATA E A HORA DO SERVIDOR + DATA E A HORA DO SERVIDOR FORMATADAS
SELECT SYSDATE "Data do Servidor", TO_CHAR (SYSDATE, 'YYYY-MM-DD HH24-MI-SS') "Data formatada"
FROM DUAL;

-- RETORNA A DATA DO SERVIDOR E O SÉCULO
SELECT SYSDATE "Data do Servidor", TO_CHAR (SYSDATE, 'SCC') "Século"
FROM DUAL;

-- RETORNA DATA DAQUI 10 DIAS (COM REFERÊNCIA NA DATA DE HOJE)
SELECT SYSDATE + 10 FROM DUAL;