-- RETORNA QUANTIDADE DE MESES ENTRE HOJE E DATA2)
SELECT MONTHS_BETWEEN(SYSDATE, TO_DATE('01-01-2019', 'DD-MM-YYYY')) FROM DUAL; -- AMBAS AS DATAS PRECISAM TEM O MESMO FORMATO
                --     DATA 1            DATA 2     -- 