SELECT * FROM TABELA_DE_CLIENTES

SELECT NOME, DATA_DE_NASCIMENTO,
CASE WHEN TO_CHAR (DATA_DE_NASCIMENTO, 'YYYY') < '1990' THEN 'VELHO(A)'
      WHEN TO_CHAR (DATA_DE_NASCIMENTO, 'YYYY') >= '1990' AND TO_CHAR (DATA_DE_NASCIMENTO, 'YYYY') <= '1995' THEN 'JOVEM'
      WHEN TO_CHAR (DATA_DE_NASCIMENTO, 'YYYY') > '1995' THEN 'CRIANÇA' END
      FROM TABELA_DE_CLIENTES;
