--Total de créditos dos clientes por estado
SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS TOTAL_CREDITO
FROM TABELA_DE_CLIENTES GROUP BY ESTADO;

--Quantas unidades de cada produto foram vendidas e valor total arrecadado com cada produto
SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) AS QUANTIDADE, SUM(PRECO) AS TOTAL_PRECO
FROM ITENS_NOTAS_FISCAIS
GROUP BY CODIGO_DO_PRODUTO;

--Maior preço por embalagem
SELECT EMBALAGEM, SUM(PRECO_DE_LISTA) AS PRECO_DE_LISTA
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM
ORDER BY PRECO_DE_LISTA DESC;

--Quantidade de produtos catalogados por embalagem
SELECT EMBALAGEM, COUNT(CODIGO_DO_PRODUTO) AS CODIGO
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM;


