--Retorna os status de acordo com o valor em coluna chamada "STATUS_PRECO"
SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA,
(CASE
    WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
    WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
    ELSE 'PRODUTO BARATO'
    END) AS STATUS_PRECO
    FROM TABELA_DE_PRODUTOS;
    
--Retorna os status de acordo com o valor em coluna chamada "STATUS_PRECO" para produtos sabor manga
SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA,
(CASE
    WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
    WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
    ELSE 'PRODUTO BARATO'
    END) AS STATUS_PRECO
    FROM TABELA_DE_PRODUTOS
    WHERE SABOR = 'Manga';

--Retorna os status de acordo com os preços em coluna chamada "STATUS_PRECO" por embalagem
SELECT EMBALAGEM, -- !!! COLUNA 1 !!!

(CASE WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO' -- !!! COLUNA 2 !!!
    WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
    ELSE 'PRODUTO BARATO' END) AS STATUS_PRECO,  -- ALIAS !

    AVG(PRECO_DE_LISTA) AS MEDIA_PRECO  -- !!! COLUNA 3 !!!    Calcula a média de preço
    FROM TABELA_DE_PRODUTOS
    GROUP BY EMBALAGEM, --AGRUPADO POR EMBALAGEM E POR STATUS DE PREÇO
    (CASE WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
    WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
    ELSE 'PRODUTO BARATO' END) --EM SUBSTITUIÇÃO AO ALIAS, AUTOMATICAMENTE CONSIDERA O "ALIAS" ANTERIOR (STATUS_PRECO)

ORDER BY EMBALAGEM ASC; 

