SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;

-- RETORNA TODOS OS CLIENTES QUE EXISTEM NOS MESMOS BAIRROS DOS VENDEDORES
SELECT * FROM TABELA_DE_CLIENTES WHERE BAIRRO
IN ('Tijuca', 'Santo Amaro', 'Jardins', 'Copacabana');

-- RETORNA TODOS OS CLIENTES QUE EXISTEM NOS MESMOS BAIRROS DOS VENDEDORES SEM PRECISAR ESPECIFICAR BAIRROS EM TODAS AS CONSULTAS
SELECT * FROM TABELA_DE_CLIENTES WHERE BAIRRO
IN (SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES);

-- (UTILIZANDO HAVING) RETORNA AS SOMAS DOS PREÇOS AGRUPADOS POR EMBALAGEM, ONDE A SOMA É MENOR OU IGUAL A 80
SELECT EMBALAGEM, SUM(PRECO_DE_LISTA) AS SOMA_PRECO
FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM
HAVING SUM(PRECO_DE_LISTA) <= 80;

-- (UTILIZANDO SUBCONSULTA) RETORNA AS SOMAS DOS PREÇOS AGRUPADOS POR EMBALAGEM, ONDE A SOMA É MENOR OU IGUAL A 80
SELECT Z.EMBALAGEM, Z.SOMA_PRECO FROM
(SELECT EMBALAGEM, SUM(PRECO_DE_LISTA) AS SOMA_PRECO
FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM) Z
WHERE Z.SOMA_PRECO <= 80;

-- (UTILIZANDO HAVING) RETORNA AS COMPRAS REALIZADAS EM 2016 CUJAS SOMAS SÃO MAIORES QUE 2000 AGRUPADAS POR CPF
SELECT CPF, COUNT(*) FROM NOTAS_FISCAIS
WHERE TO_CHAR(DATA_VENDA, 'YYYY') = '2016'
GROUP BY CPF
HAVING COUNT(*) > 2000;

-- (UTILIZANDO SUBCONSULTA) RETORNA AS COMPRAS REALIZADAS EM 2016 CUJAS SOMAS SÃO MAIORES QUE 2000 AGRUPADAS POR CPF
SELECT Z.CPF, Z.NOTAS FROM
(SELECT CPF, COUNT(*) AS NOTAS FROM NOTAS_FISCAIS
WHERE TO_CHAR(DATA_VENDA, 'YYYY') = '2016'
GROUP BY CPF) Z
WHERE Z.NOTAS > 2000;


