SELECT * FROM NOTAS_FISCAIS;
SELECT * FROM ITENS_NOTAS_FISCAIS;

-- OBTEM O FATURAMENTO ANUAL 
SELECT TO_CHAR(DATA_VENDA, 'YYYY') AS ANO, SUM(QUANTIDADE * PRECO) AS FATURAMENTO  -- FILTRA O ANO, SOMA TODOS OS FATURAMENTOS
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO  -- JUNTA AS DUAS TABELAS
GROUP BY TO_CHAR(DATA_VENDA, 'YYYY'); -- AGRUPA OS DADOS POR ANO
