-- (UTILIZANDO SUBCONSULTA) RETORNA AS SOMAS DOS PREÇOS AGRUPADOS POR EMBALAGEM, ONDE A SOMA É MENOR OU IGUAL A 80
SELECT Z.EMBALAGEM, Z.SOMA_PRECO FROM
(SELECT EMBALAGEM, SUM(PRECO_DE_LISTA) AS SOMA_PRECO
FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM) Z
WHERE Z.SOMA_PRECO <= 80;

-- CRIADA VIEW DO SCRIPT ABAIXO (NOME: VW_SOMA_PRECOS_POR_EMBALAGEM):
SELECT EMBALAGEM, SUM(PRECO_DE_LISTA) AS SOMA_PRECO
FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM

-- SUBSTITUINDO A VIEW CRIADA NO PRIMEIRO SCRIPT:
SELECT Z.EMBALAGEM, Z.SOMA_PRECO FROM
(VW_SOMA_PRECOS_POR_EMBALAGEM) Z
WHERE Z.SOMA_PRECO <= 80;



-- *** OUTRAS FORMAS DE USAR A VIEW CRIADA *** --

-- Retorna resultado da view
SELECT * FROM VW_SOMA_PRECOS_POR_EMBALAGEM;

-- Retorna dados em comum entre a tabela de produtos e a view
SELECT * FROM TABELA_DE_PRODUTOS A
INNER JOIN VW_SOMA_PRECOS_POR_EMBALAGEM B
ON A.EMBALAGEM = B.EMBALAGEM;
