SELECT * FROM TABELA_DE_CLIENTES;

-- MOSTRA A IDADE QUE A PESSOA COMPLETA NO ANO ATUAL
SELECT * FROM TABELA_DE_CLIENTES;
SELECT NOME, TO_CHAR(SYSDATE, 'YYYY') - TO_CHAR (DATA_DE_NASCIMENTO, 'YYYY')
AS IDADE_ATUAL FROM TABELA_DE_CLIENTES;

-- MOSTRA A IDADE QUE A PESSOA TEM NA DATA ATUAL, PORÉM COM  CASAS DECIMAIS
SELECT NOME, MONTHS_BETWEEN (SYSDATE, DATA_DE_NASCIMENTO)/12 AS IDADE
FROM TABELA_DE_CLIENTES;

-- MOSTRA A IDADE QUE A PESSOA TEM NA DATA ATUAL (ARREDONDADO)
SELECT NOME, TRUNC (MONTHS_BETWEEN (SYSDATE, DATA_DE_NASCIMENTO)/12) AS IDADE
FROM TABELA_DE_CLIENTES;


