SELECT * FROM NOTAS_FISCAIS;

SELECT * FROM ITENS_NOTAS_FISCAIS;

-- RETORNA O VALOR TOTAL DE IMPOSTOS DO ANO 2016
SELECT TO_CHAR(A.DATA_VENDA, 'YYYY') AS ANO, FLOOR(SUM(B.QUANTIDADE * B.PRECO * A.IMPOSTO)) AS IMPOSTO
FROM NOTAS_FISCAIS A
INNER JOIN ITENS_NOTAS_FISCAIS B
ON A.NUMERO = B.NUMERO
WHERE TO_CHAR(A.DATA_VENDA, 'YYYY') = 2016
GROUP BY TO_CHAR(A.DATA_VENDA, 'YYYY');
