-- RETORNA ENDEREÇO E BAIRRO JUNTOS;
SELECT CONCAT(ENDERECO_1, BAIRRO) FROM TABELA_DE_CLIENTES;

-- RETORNA ENDEREÇO COMPLETO CONCATENADO;
SELECT NOME, (' ' || ENDERECO_1 || ', ' || BAIRRO || ' - '  || CIDADE || '/ '  || ESTADO || ', '  || 'CEP: ' || CEP)
AS ENDERECO FROM TABELA_DE_CLIENTES 