
-- RETORNA A POSIÇÃO EM QUE ESTÁ O CARACTETE TRAÇO "-"
SELECT NOME_DO_PRODUTO, INSTR(NOME_DO_PRODUTO, '-')
FROM TABELA_DE_PRODUTOS;

-- RETORNA A POSIÇÃO EM QUE ESTÁ O CARACTETE "ml"
SELECT NOME_DO_PRODUTO, INSTR(NOME_DO_PRODUTO, 'ml')
FROM TABELA_DE_PRODUTOS;