
-- RETORNA "AAAAA" SEM ESPAÇOS EM BRANCO À DIREITA
SELECT RTRIM('AAAAA       ') FROM DUAL;  -- DUAL SIGNIFICA QUE É UM SELECT NEUTRO, NÃO ESTÁ BUSCANDO DADOS DE TABELA. NÃO FUNCIONA SE EU INFORMAR O NOME DE UM CAMPO DE TABELA.