
-- RETORNA A "L" EM LUGAR DE "Litros"
SELECT NOME_DO_PRODUTO, REPLACE(NOME_DO_PRODUTO, 'Litro', 'L') 
FROM TABELA_DE_PRODUTOS

-- CORRIGE A PALAVRA "LS" DO REPLACE DA CONSULTA ACIMA, POIS ALGUNS ITENS ESTAVAM COMO "Litros" (REPLACE DO REPLACE)
SELECT NOME_DO_PRODUTO, REPLACE (REPLACE(NOME_DO_PRODUTO, 'Litro', 'L'), 'Ls', 'L') FROM TABELA_DE_PRODUTOS;




