
-- RETORNA "AAAAA" SEM ESPAÇOS EM BRANCO À ESQUERDA
SELECT LTRIM('        AAAAA') FROM DUAL;  -- DUAL SIGNIFICA QUE É UM SELECT NEUTRO, NÃO ESTÁ BUSCANDO DADOS DE TABELA. NÃO FUNCIONA SE EU INFORMAR O NOME DE UM CAMPO DE TABELA.