
-- RETORNA DO 3º AO 5º CARACTERE DOS DADOS DA COLUNA "NOME_DO_PRODUTO"
SELECT NOME_DO_PRODUTO, SUBSTR(NOME_DO_PRODUTO, 3, 5) FROM TABELA_DE_PRODUTOS;

-- RETORNA DO 1º AO 3º CARACTERE DOS DADOS DA COLUNA "NOME_DO_PRODUTO"
SELECT NOME_DO_PRODUTO, SUBSTR(NOME_DO_PRODUTO, 1, 3) FROM TABELA_DE_PRODUTOS;