
-- RETORNA O MAIOR VALOR
SELECT GREATEST (10, 20, 15) FROM DUAL

-- RETORNA COLUNAS VOLUME_DE_COMPRA, LIMITE_DE_CREDITO E MAIOR ENTRE AS DUAS. 
SELECT VOLUME_DE_COMPRA, LIMITE_DE_CREDITO,
GREATEST (VOLUME_DE_COMPRA, LIMITE_DE_CREDITO) FROM TABELA_DE_CLIENTES;