SELECT TO_CHAR (SYSDATE, 'YYYY') FROM DUAL;
SELECT TO_CHAR (SYSDATE, 'MM-YYYY') FROM DUAL;
SELECT TO_CHAR (SYSDATE, 'DD') FROM DUAL;
SELECT TO_CHAR (SYSDATE, 'DD-MM-YYYY HH24:MM:SS') FROM DUAL;


-- RETORNA DATA, HORA NO FORMATO 12 HORAS E O PERÍODO, MANHÃ OU TARDE.
SELECT TO_CHAR (SYSDATE, 'DD-MM-YYYY HH12:MM:SS AM') FROM DUAL;


    -- PREENCHE O NÚMERO COM A QUANTIDADE DE ZEROS INFORMADA
SELECT TO_CHAR (10, '00000') FROM DUAL;