
SELECT EXTRACT (MONTH FROM (TO_DATE ('12/04/2014', 'DD/MM/YYYY')) ) FROM DUAL;

SELECT EXTRACT (MONTH FROM SYSDATE) FROM DUAL;

SELECT EXTRACT (DAY FROM SYSDATE) FROM DUAL;

SELECT EXTRACT (YEAR FROM (TO_DATE ('12/04/2014', 'DD/MM/YYYY'))) AS ANO FROM DUAL;



